### PR TITLE
feat(projects): exposed the project capability from the Launch Darkly APIs

### PR DESCRIPTION
**Pull request by Younis-NAB**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Have you created new unit?
2. [x] Does your submission pass all tests?
3. [x] Have you lint your code locally prior to submission (automated)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

NOTE: The update project hasn't been exposed via the command line utilities.

### CODE REVIEW

**Comment by wyvern8** [comment]
tested ready for review @Younis-NAB ?   i've approved the codeclimate things.

**Comment by wyvern8** [comment]
code looks good to me, but have not tested yet.  any comments @Neko-Design ?

**Comment by Younis-NAB** [comment]
@wyvern8 , PR is now ready, had few testing cases to follow up with

Note that I haven't exposed update to the ldutils, I would need to have a good thinking about how best to play this as we might be best expose this for a number of attributes.

**Review by wyvern8 — APPROVED** [review]
lgtm 🚀

**Pull request merged**
