### PR TITLE
Feature/user management

### PR DESCRIPTION
**Pull request by Neko-Design**
### All Submissions:

* [ x ] Have you followed the guidelines in our Contributing document?
* [ x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Feature Submissions:

1. [ x ] Have you created new unit?
2. [ x ] Does your submission pass all tests?
3. [ x ] Have you lint your code locally prior to submission (automated)?

### CODE REVIEW

**Comment by Neko-Design** [comment]
This PR implements #38

**Comment by wyvern8** [comment]
lgtm - very useful.

**Review by wyvern8 — APPROVED** [review]
:rocket:

**Pull request merged**
