### PR TITLE
feat(flags): add bulkMigrateFeatureFlags mode

### PR DESCRIPTION
**Pull request by wyvern8**
### All Submissions:

* [yes ] Have you followed the guidelines in our Contributing document?
* [yes ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New Feature Submissions:

1. [ yes] Have you created new unit?
2. [ yes] Does your submission pass all tests?
3. [ yes] Have you lint your code locally prior to submission (automated)?

### CODE REVIEW

**Review by Neko-Design — APPROVED** [review]
Nice and simple change, calling an existing function. Documentation looks good, think more examples of the command line app could be useful? All good :)

**Comment by wyvern8** [comment]
yeah, probably some further examples would be worth adding.  next i'm thinking about catering for release rollback.  could use getFeatureFlags before release as part of migrate job to capture the current project state to json, and then we need a mode along the lines of:
 `restoreFeatureFlags <proj> <target> <env> <flagNames> <backupJsonFile>` 
..that iterates over flagNames supplied, looks at backupJson, and patches the target env..  a little unclear if you could end up with hybrid config with the patch approach..

**Comment by wyvern8** [comment]
looks like if we add an example to jsdoc for each function it will be rendered in API.md as part of build. eg.

`@example ldutils migrateFeatureFlag my-project my-flag dev test`

**Pull request merged**
